/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.funshion.test;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ResCodeConstant implements org.apache.thrift.TEnum {
  DEFAULT_CODE(0),
  REQ_PARAM_ERROR(1001),
  REQ_COOKIE_ISEXPIRED(1002),
  BUS_COOKIE_NOT_EXIST(3001),
  REDIS_ERROR(4001),
  NETWORK_ERROR(5001);

  private final int value;

  private ResCodeConstant(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ResCodeConstant findByValue(int value) { 
    switch (value) {
      case 0:
        return DEFAULT_CODE;
      case 1001:
        return REQ_PARAM_ERROR;
      case 1002:
        return REQ_COOKIE_ISEXPIRED;
      case 3001:
        return BUS_COOKIE_NOT_EXIST;
      case 4001:
        return REDIS_ERROR;
      case 5001:
        return NETWORK_ERROR;
      default:
        return null;
    }
  }
}
